dataset:
  path: "C:/Users/sashe/mlops/data/01_homely_resort_listing.csv"
setup:
  feature_selection: True
  n_features_to_select : 0.45
  remove_multicollinearity: True
  multicollinearity_threshold: 0.9
model:
  path: "../../../../models/regression"